version: "3"

services:
  stage1:
    privileged: true
    build:
      context: ./webapp
    volumes:
      - /dev:/dev
      - type: bind
        source: ./mount
        target: /app/mount
        bind:
          propagation: shared
      - type: bind
        source: ./volume.img
        target: /app/volume.img
        bind:
          propagation: shared
    ports:
      - 127.0.0.1:8000:8000

  stage2:
    image: bash
    volumes:
      - type: bind
        source: ./mount
        target: /app
        bind:
          propagation: shared
    depends_on:
      - stage1
    entrypoint: [ "bash", "-c", "until [ -f /app/healthy ]; do echo waiting; sleep 5; done" ]

  database:
    image: mysql
    volumes:
      - ./mount/mysql:/var/lib/mysql:shared
    environment: 
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      stage2:
        condition: service_completed_successfully

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 127.0.0.1:8001:80
    environment:
      PMA_HOST: database
    depends_on:
      - database