version: "3"

services:
  database:
    image: mysql
    restart: unless-stopped
    volumes:
      - ./mount/mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports: 
      - 127.0.0.1:8001:80
    environment:
      PMA_HOST: database
    depends_on:
      - database
